version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  pago:
    build:
      context: ./pagos
    container_name: pagos
    depends_on:
      - rabbitmq
    ports:
      - "5005:5005"

  reservas:
    build:
      context: ./reservas
    container_name: reservas
    depends_on:
      - rabbitmq
